### ISSUE TITLE
Select Evaluator and sampler

### ISSUE THREAD

**Issue by mohit-chawla** [mohit-chawla/recboard#43]

**Comment by kriticism** [comment]
#59 
This makes evaluators selectable + usable, and one train sampler useable. Happy path for BPR and mentioned in PR.

^ requires pulling openrec submodule changes from here: https://github.com/kriticism/openrec

**Comment by kriticism** [comment]
This PR adds the infra structure for selecting evaluator, sampler (and using some of them).

Final shape of the app will build upon it.
